### PR TITLE
That way we rvm users can use it too!

### PR DESCRIPTION
**Pull request by jc00ke**

### CODE REVIEW

**Comment by maxim** [comment]
I actually did this on purpose, being an rvm user myself. I have different projects running in different rubies/gemsets, yet I wanted takeup to be independent simple script that just happens to be in ruby. For that reason I wanted to bypass rvm and use the "system" ruby, like I do for any of my peripheral project-independent scripts. Is there a better way to achieve that?

**Comment by jc00ke** [comment]
I thought env would pick whichever Ruby was available, including your system Ruby?

What's the output from `/usr/bin/env ruby -v` ? Is it your system Ruby?

**Comment by maxim** [comment]
That's correct. What I tried to do is avoid having takeup executed by different rubies with different gemsets every time I work on a different project. Instead, make it use the same ruby no matter what rvm is set to. Although, since it doesn't rely on anything but yaml, it'd likely work just fine anywhere. Thoughts?

**Comment by jc00ke** [comment]
Ah, ok I think I understand more now. In my case, I only have the rvm ruby. I'm on Ubuntu & I don't have a system `/usr/bin/ruby` I only have `/usr/bin/env ruby` through rvm. Have you seen a specific problem with running takeup with different rubies & different gemsets? It just runs the manifest.yml that matches the current directory, so it should "just work."

**Comment by maxim** [comment]
Yeah, runs fine on 1.8.7, ree, and 1.9.2, so I'll merge it. Will deal with exotic cases once they occur. : ) This thing really just needs a proper install script where you can configure ruby, color usage, manifest path, etc.

**Comment by jc00ke** [comment]
Cool, thanks for the pull!

**Pull request merged**
